# -*- coding: utf-8 -*-
"""langgraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZgo76PA4PHn6hP4wXG6WVqSCcTU1QIp
"""

!pip install -q \
langgraph \
langchain-core \
langchain-community \
gradio \
huggingface_hub

from typing import TypedDict

from langgraph.graph import StateGraph, END

from huggingface_hub import InferenceClient

HF_TOKEN = "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"

client = InferenceClient(
    model="meta-llama/Llama-3.1-8B-Instruct",
    token=HF_TOKEN
)

def generate_response(prompt):

    response = client.chat_completion(
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        max_tokens=500
    )

    return response.choices[0].message.content

class CareerState(TypedDict):
    skills: str
    experience: str
    goal: str

    analysis: str
    advice: str
    roadmap: str

def analyze_profile(state):

    prompt = f"""
    Analyze this candidate:

    Skills:
    {state['skills']}

    Experience:
    {state['experience']}

    Goal:
    {state['goal']}

    Give strengths and weaknesses.
    """

    result = generate_response(prompt)

    return {
        "analysis": result
    }

def career_advice(state):

    prompt = f"""
    Based on this analysis:

    {state['analysis']}

    Provide career advice.
    """

    result = generate_response(prompt)

    return {
        "advice": result
    }

def learning_roadmap(state):

    prompt = f"""
    Goal:

    {state['goal']}

    Create a 3 month roadmap.
    """

    result = generate_response(prompt)

    return {
        "roadmap": result
    }

builder = StateGraph(CareerState)

builder.add_node("analyze", analyze_profile)
builder.add_node("advice", career_advice)
builder.add_node("roadmap", learning_roadmap)

builder.set_entry_point("analyze")

builder.add_edge("analyze", "advice")
builder.add_edge("advice", "roadmap")
builder.add_edge("roadmap", END)

graph = builder.compile()

def run_agent(skills, experience, goal):

    result = graph.invoke(
        {
            "skills": skills,
            "experience": experience,
            "goal": goal
        }
    )

    return f"""
## Profile Analysis

{result['analysis']}

---

## Career Advice

{result['advice']}

---

## Learning Roadmap

{result['roadmap']}
"""

import gradio as gr

demo = gr.Interface(
    fn=run_agent,
    inputs=[
        gr.Textbox(label="Skills"),
        gr.Textbox(label="Experience"),
        gr.Textbox(label="Career Goal")
    ],
    outputs=gr.Markdown(),
    title="LangGraph Career Advisor"
)

demo.launch(share=True, debug=True)
